INSERT INTO productos (nombre, descripcion, precio, img, stock) VALUES
('Mouse Gamer', 'Mouse óptico de alta precisión para gaming', 3500, 'https://via.placeholder.com/150', 50),
('Teclado Mecánico', 'Teclado mecánico con retroiluminación RGB', 8000, 'https://via.placeholder.com/150', 30),
('Monitor Full HD', 'Monitor de 24 pulgadas con resolución Full HD', 15000, 'https://via.placeholder.com/150', 20),
('Auriculares Inalámbricos', 'Auriculares Bluetooth con cancelación de ruido', 6000, 'https://via.placeholder.com/150', 25),
('Cámara Web HD', 'Cámara web de alta definición para streaming y videollamadas', 4000, 'https://via.placeholder.com/150', 15),
('Almacenamiento SSD 500GB', 'Disco sólido SSD de 500GB para mayor velocidad', 12000, 'https://via.placeholder.com/150', 10),
('Fuente de Poder 600W', 'Fuente de poder de 600W para sistemas gaming', 7000, 'https://via.placeholder.com/150', 40),
('Gabinete ATX RGB', 'Gabinete ATX con iluminación RGB y espacio para refrigeración líquida', 9000, 'https://via.placeholder.com/150', 35),
('Placa Base ATX', 'Placa base ATX compatible con procesadores Intel y AMD', 11000, 'https://via.placeholder.com/150', 20),
('Tarjeta Gráfica GTX 1660', 'Tarjeta gráfica NVIDIA GTX 1660 para gaming en 1080p', 25000, 'https://via.placeholder.com/150', 5),
('Procesador Intel i5', 'Procesador Intel Core i5 de décima generación', 20000, 'https://via.placeholder.com/150', 8),
('Memoria RAM 16GB', 'Memoria RAM DDR4 de 16GB para multitarea fluida', 7000, 'https://via.placeholder.com/150', 30),
('Disco Duro 1TB', 'Disco duro mecánico de 1TB para almacenamiento masivo', 4000, 'https://via.placeholder.com/150', 50),
('Refrigeración Líquida AIO', 'Sistema de refrigeración líquida todo en uno para CPU', 12000, 'https://via.placeholder.com/150', 15),
('Teclado Ergonómico', 'Teclado ergonómico con soporte para muñecas', 5000, 'https://via.placeholder.com/150', 20),
('Silla Gamer', 'Silla gamer ergonómica con reposabrazos ajustables', 15000, 'https://via.placeholder.com/150', 10),
('Cable HDMI 2.0', 'Cable HDMI 2.0 de alta velocidad para video y audio', 800, 'https://via.placeholder.com/150', 100),
('Hub USB 3.0', 'Hub USB 3.0 con 4 puertos para expansión de conectividad', 1200, 'https://via.placeholder.com/150', 60),
('Adaptador WiFi USB', 'Adaptador WiFi USB para conexión inalámbrica a internet', 1500, 'https://via.placeholder.com/150', 45),
('Cargador Rápido USB-C', 'Cargador rápido USB-C para dispositivos móviles', 2000, 'https://via.placeholder.com/150', 70),
('Cable de Red Ethernet', 'Cable de red Ethernet CAT6 para conexión a internet', 500, 'https://via.placeholder.com/150', 80),
('Soporte para Monitor', 'Soporte ajustable para monitor con brazo articulado', 3000, 'https://via.placeholder.com/150', 25),
('Alfombrilla de Ratón Grande', 'Alfombrilla de ratón grande con superficie suave', 1000, 'https://via.placeholder.com/150', 90),
('Lámpara LED Escritorio', 'Lámpara LED regulable para escritorio con puerto USB', 2500, 'https://via.placeholder.com/150', 40),
('Mouse Gamer', 'Mouse óptico de alta precisión para gaming', 3500, 'https://via.placeholder.com/150', 50);
